bands: @import("Bands.zig") = .{},
hits: @import("HitMap.zig") = .{},
band_hits: @import("BandHitMap.zig") = .{},
sidebar_regions: @import("SidebarRegions.zig") = .{},
workspace: ?@import("telar-core").WorkspaceId = null,
