//! Exact geometry context plus a fingerprint of the complete source span.
text_hash: u64,
text_len: usize,
owner: @import("MessageLayoutOwner.zig"),
font_identity: u64,
font_revision: u64,
width: f32,
start_x: f32,
row: f32,
scale: f32,
pixel_height: u16,
cell_width: u32,
cell_height: u32,
face: @import("label_face.zig").Face,
bold: bool,
italic: bool,
viewport_top: f32 = 0,
viewport_bottom: f32 = 0,
