const core = @import("telar-core");

id: []const u8 = "",
source_turn: []const u8 = "",
identity: u64 = 0,
role: core.agent_thread.Role,
kind: ?core.agent_thread.ItemKind = null,
status: ?core.agent_thread.ItemStatus = null,
phase: ?core.agent_thread.MessagePhase = null,
parent_identity: ?u64 = null,
turn_identity: ?u64 = null,
title: ?[]const u8 = null,
detail: ?[]const u8 = null,
reference: ?[]const u8 = null,
text: []const u8 = "",
retain_text: bool = false,
append: bool = false,
complete: bool = false,
truncated: bool = false,
