pub const RequestsGroup = enum {
    change_review_query,
    change_review_command,
    initial_open,
    workspace_operation,
    workspace_snapshot,
    tab_snapshot,
    pane_operation,
    attachment,
    tab_operation,
    notification,
    editor_open,
    peek_screen,
    ignored,
};
