const State = @This();
const source_namespace = @import("state_support.zig");
const workspace = @import("workspace_support.zig");
items: [source_namespace.max_workspaces]?workspace.Workspace = [_]?workspace.Workspace{null} ** source_namespace.max_workspaces,
count: usize = 0,
git_probe: ?@import("telar-core").schema.WorkspaceId = null,
next_workspace_id: u64 = 1,
next_tab_id: u64 = 1,
revision: u64 = 1,
