pane_id: @import("telar-core").PaneId,
kind: enum { submit, interrupt, approve, decline, review, remove_image, preview_image, close_image },
approval_id: u64 = 0,
image_index: u8 = 0,
composer_revision: u64 = 0,
