//! Synchronous paint input; text is borrowed only while geometry is appended.
owner: @import("../MessageLayoutOwner.zig"),
offset: u32,
text: []const u8,
bounds: @import("../../render/Rect.zig"),
viewport: @import("../../render/Rect.zig"),
advance: f32,
face: @FieldType(@import("../Label.zig"), "face"),
bold: bool = false,
pixel_height: u16,
