const std = @import("std");
const tls = @import("tls.zig");

const c = @cImport({
    @cInclude("nghttp2/nghttp2.h");
});

// HTTP/2, observed rather than proxied.
//
// A real h2 proxy terminates both sides: it owns two sessions, maps stream ids
// between them, mirrors flow-control windows and re-encodes every header block.
// That is a subproject, and none of it is needed to *see* the conversation.
//
// This relays frames byte for byte — the two endpoints negotiate h2 with each
// other even though TLS is terminated in the middle — and feeds a copy through
// nghttp2's standalone HPACK inflater to read what went past. No sessions, no
// stream mapping, no windows, no frames generated by us.
//
// The limitation is the obvious one: passing bytes through means not changing
// them. Modifying an h2 stream needs the full two-session proxy, and that is the
// step where re-encoding HPACK becomes unavoidable.

pub const frame_header_len = 9;

pub const FrameType = enum(u8) {
    data = 0x0,
    headers = 0x1,
    priority = 0x2,
    rst_stream = 0x3,
    settings = 0x4,
    push_promise = 0x5,
    ping = 0x6,
    goaway = 0x7,
    window_update = 0x8,
    continuation = 0x9,
    _,
};

/// The connection preface a client sends before its first frame.
pub const client_preface = "PRI * HTTP/2.0\r\n\r\nSM\r\n\r\n";

const flag_end_headers: u8 = 0x4;
const flag_padded: u8 = 0x8;
const flag_priority: u8 = 0x20;

/// One direction's HPACK state. The dynamic table is per-direction and strictly
/// ordered, so a decoder must see every header block in sequence — which is
/// exactly what sitting inline gives us.
pub const Decoder = struct {
    inflater: ?*c.nghttp2_hd_inflater = null,
    /// Header blocks can span CONTINUATION frames; they are only inflated once
    /// END_HEADERS arrives.
    block: std.ArrayList(u8) = .empty,
    gpa: std.mem.Allocator,

    pub fn init(gpa: std.mem.Allocator) !Decoder {
        var self: Decoder = .{ .gpa = gpa };
        if (c.nghttp2_hd_inflate_new(&self.inflater) != 0) {
            return error.InflaterFailed;
        }
        return self;
    }

    pub fn deinit(self: *Decoder) void {
        if (self.inflater) |inf| {
            c.nghttp2_hd_inflate_del(inf);
        }
        self.block.deinit(self.gpa);
    }

    /// Inflates one complete header block into `out` as `name: value` lines.
    fn emit(self: *Decoder, out: *std.Io.Writer) void {
        const inf = self.inflater orelse return;
        var input = self.block.items;

        while (true) {
            var nv: c.nghttp2_nv = undefined;
            var flags: c_int = 0;
            const consumed = c.nghttp2_hd_inflate_hd2(
                inf,
                &nv,
                &flags,
                input.ptr,
                input.len,
                1, // in_final
            );
            if (consumed < 0) {
                break;
            }
            input = input[@intCast(consumed)..];

            if (flags & c.NGHTTP2_HD_INFLATE_EMIT != 0) {
                out.print("{s}: {s}\n", .{
                    nv.name[0..nv.namelen],
                    nv.value[0..nv.valuelen],
                }) catch {};
            }
            if (flags & c.NGHTTP2_HD_INFLATE_FINAL != 0) {
                break;
            }
            if (input.len == 0) {
                break;
            }
        }

        _ = c.nghttp2_hd_inflate_end_headers(inf);
        self.block.clearRetainingCapacity();
    }
};

/// What one direction saw. Bodies are capped by the caller's buffer.
pub const Observed = struct {
    frames: usize = 0,
    headers: usize = 0,
    data_bytes: u64 = 0,
    truncated: bool = false,
};

/// Relays one direction and reports what went by.
///
/// `text` receives decoded headers, `body` the DATA payloads. Both are the
/// caller's buffers and both may fill up; the relay itself never stops.
pub fn relay(session: *tls.Session, from: tls.Session.Side, to: tls.Session.Side, decoder: *Decoder, text: *std.Io.Writer, body: []u8, body_len: *usize, seen: *Observed) void {
    // Carries the bytes of a frame that a single read did not deliver whole.
    var pending: std.ArrayList(u8) = .empty;
    defer pending.deinit(decoder.gpa);

    var chunk: [32 * 1024]u8 = undefined;
    var preface_left: usize = if (from == .child) client_preface.len else 0;

    while (true) {
        const n = session.read(from, &chunk) orelse break;
        // Forward first and unchanged: observation must never delay or alter the
        // conversation it is watching.
        if (!session.writeAll(to, chunk[0..n])) {
            break;
        }

        var input: []const u8 = chunk[0..n];

        // The client preface is not a frame; skip past it once.
        if (preface_left > 0) {
            const skip = @min(preface_left, input.len);
            preface_left -= skip;
            input = input[skip..];
            if (input.len == 0) {
                continue;
            }
        }

        pending.appendSlice(decoder.gpa, input) catch {
            pending.clearRetainingCapacity();
            continue;
        };

        // Drain as many complete frames as the buffer now holds.
        while (pending.items.len >= frame_header_len) {
            const h = pending.items;
            const payload_len: usize = (@as(usize, h[0]) << 16) | (@as(usize, h[1]) << 8) | h[2];
            const total = frame_header_len + payload_len;
            if (pending.items.len < total) {
                break;
            }

            const kind: FrameType = @enumFromInt(h[3]);
            const flags = h[4];
            var payload = pending.items[frame_header_len..total];
            seen.frames += 1;

            switch (kind) {
                .headers, .push_promise, .continuation => {
                    if (kind == .headers) {
                        // Strip the parts that are not part of the header block.
                        if (flags & flag_padded != 0 and payload.len >= 1) {
                            const pad = payload[0];
                            payload = payload[1..];
                            if (payload.len >= pad) {
                                payload = payload[0 .. payload.len - pad];
                            }
                        }
                        if (flags & flag_priority != 0 and payload.len >= 5) {
                            payload = payload[5..];
                        }
                    }
                    decoder.block.appendSlice(decoder.gpa, payload) catch {};
                    if (flags & flag_end_headers != 0) {
                        seen.headers += 1;
                        text.print("\n--- stream {d} ---\n", .{streamId(h)}) catch {};
                        decoder.emit(text);
                    }
                },
                .data => {
                    seen.data_bytes += payload.len;
                    const room = body.len - body_len.*;
                    const take = @min(room, payload.len);
                    if (take > 0) {
                        @memcpy(body[body_len.* .. body_len.* + take], payload[0..take]);
                        body_len.* += take;
                    }
                    if (take < payload.len) {
                        seen.truncated = true;
                    }
                },
                else => {},
            }

            // std.ArrayList has no cheap pop-front; a copy is fine at frame size.
            const rest = pending.items.len - total;
            std.mem.copyForwards(u8, pending.items[0..rest], pending.items[total..]);
            pending.shrinkRetainingCapacity(rest);
        }
    }
}

fn streamId(header: []const u8) u32 {
    return (@as(u32, header[5] & 0x7F) << 24) |
        (@as(u32, header[6]) << 16) |
        (@as(u32, header[7]) << 8) |
        @as(u32, header[8]);
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

const testing = std.testing;

test "reads the frame header layout" {
    // length 0x000004, type SETTINGS, flags 0, stream 0
    const h = [_]u8{ 0x00, 0x00, 0x04, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00 };
    const len: usize = (@as(usize, h[0]) << 16) | (@as(usize, h[1]) << 8) | h[2];
    try testing.expectEqual(@as(usize, 4), len);
    try testing.expectEqual(FrameType.settings, @as(FrameType, @enumFromInt(h[3])));
    try testing.expectEqual(@as(u32, 0), streamId(&h));
}

test "stream id ignores the reserved bit" {
    // The top bit of the stream id field is reserved and must be masked off.
    const h = [_]u8{ 0, 0, 0, 0x01, 0x04, 0x80, 0x00, 0x00, 0x0D };
    try testing.expectEqual(@as(u32, 13), streamId(&h));
}

test "inflates a header block that nghttp2 deflated" {
    const gpa = testing.allocator;

    var deflater: ?*c.nghttp2_hd_deflater = null;
    try testing.expectEqual(@as(c_int, 0), c.nghttp2_hd_deflate_new(&deflater, 4096));
    defer c.nghttp2_hd_deflate_del(deflater);

    var nva = [_]c.nghttp2_nv{
        .{ .name = @constCast(":method"), .value = @constCast("POST"), .namelen = 7, .valuelen = 4, .flags = 0 },
        .{ .name = @constCast(":path"), .value = @constCast("/v1/messages"), .namelen = 5, .valuelen = 12, .flags = 0 },
        .{ .name = @constCast("x-test"), .value = @constCast("hola"), .namelen = 6, .valuelen = 4, .flags = 0 },
    };

    var buf: [1024]u8 = undefined;
    const written = c.nghttp2_hd_deflate_hd(deflater, &buf, buf.len, &nva, nva.len);
    try testing.expect(written > 0);

    var decoder = try Decoder.init(gpa);
    defer decoder.deinit();
    try decoder.block.appendSlice(gpa, buf[0..@intCast(written)]);

    var out_buf: [1024]u8 = undefined;
    var w = std.Io.Writer.fixed(&out_buf);
    decoder.emit(&w);
    const out = w.buffered();

    try testing.expect(std.mem.indexOf(u8, out, ":method: POST") != null);
    try testing.expect(std.mem.indexOf(u8, out, ":path: /v1/messages") != null);
    try testing.expect(std.mem.indexOf(u8, out, "x-test: hola") != null);
}

test "the dynamic table carries across blocks" {
    // The second block references the first's entries, so decoding it alone
    // would fail. This is why the decoder must see every block in order.
    const gpa = testing.allocator;

    var deflater: ?*c.nghttp2_hd_deflater = null;
    try testing.expectEqual(@as(c_int, 0), c.nghttp2_hd_deflate_new(&deflater, 4096));
    defer c.nghttp2_hd_deflate_del(deflater);

    var nva = [_]c.nghttp2_nv{
        .{ .name = @constCast("x-herdr-pane"), .value = @constCast("7"), .namelen = 12, .valuelen = 1, .flags = 0 },
    };

    var first: [512]u8 = undefined;
    const n1 = c.nghttp2_hd_deflate_hd(deflater, &first, first.len, &nva, nva.len);
    var second: [512]u8 = undefined;
    const n2 = c.nghttp2_hd_deflate_hd(deflater, &second, second.len, &nva, nva.len);
    try testing.expect(n1 > 0 and n2 > 0);
    // The repeat is far smaller: it is a reference into the dynamic table.
    try testing.expect(n2 < n1);

    var decoder = try Decoder.init(gpa);
    defer decoder.deinit();

    var out_buf: [512]u8 = undefined;
    for ([_][]const u8{ first[0..@intCast(n1)], second[0..@intCast(n2)] }) |block| {
        try decoder.block.appendSlice(gpa, block);
        var w = std.Io.Writer.fixed(&out_buf);
        decoder.emit(&w);
        try testing.expect(std.mem.indexOf(u8, w.buffered(), "x-herdr-pane: 7") != null);
    }
}
