const Snapshot = @This();
const source_namespace = @import("telemetry.zig");
const runtime_transport = @import("../entrypoints/runtime_io.zig");
const client_model = @import("telar-client").model;
const kitty = @import("../../graphics/root.zig").kitty;
theme_name: []const u8,
icon_theme_name: []const u8,
active_tab: source_namespace.schema.TabId,
tab_count: usize,
focused_pane: source_namespace.schema.PaneId,
pane_count: usize,
pending_updates: usize,
draw_pending: bool,
media_pending: bool,
outbox: runtime_transport.Snapshot,
capabilities: client_model.HostCapabilities,
zlib_support: kitty.Support = .unknown,
sidebar_rendering: kitty.ResolvedSidebarRendering,
lua_used: usize,
lua_limit: usize,
kitty_store_bytes: usize,
toast_cache_bytes: usize,
sidebar_cache_bytes: usize,
icon_cache_bytes: usize,
modal_cache_bytes: usize,
pill_cache_bytes: usize = 0,
attachment_cache_bytes: usize,
screen_bytes: usize,
shared_expiries: u8,
shared_retire_latency: source_namespace.diagnostics.Timing,
heap: source_namespace.diagnostics.Heap.Snapshot,
