const TransformCase = @This();
const request = @import("request_support.zig");
const middleware = @import("../middleware.zig");
dialect: request.ApiDialect = .anthropic_messages,
direction: middleware.Direction = .request,
kind: middleware.HeaderKind = .request,
method: []const u8 = "POST",
target: []const u8 = "/v1/messages",
encoding: ?[]const u8 = "gzip, br",
