const RenderInput = @This();
const source_namespace = @import("view.zig");
const agents_module = @import("telar-client").agents;
const notifications_module = @import("telar-client").notifications;
const name_prompt = @import("telar-client").model.name_prompt;
const history_palette_state = @import("telar-client").model.history_palette;
const suggestion_state = @import("telar-client").model.suggestion;
const client_model = @import("telar-client").model;
const widgets = @import("../../widgets/root.zig");
const bars = @import("../../bars/root.zig");
tabs: ?*const source_namespace.tabs_mod.Model = null,
model: *const source_namespace.multiplexer.Model,
compositor: ?*const source_namespace.multiplexer.Compositor = null,
agents: *const agents_module.Snapshot = &source_namespace.empty_agent_snapshot,
sidebar_animation_frame: u8 = 0,
notifications: *const notifications_module.Center = &source_namespace.empty_notifications,
workspaces: *const source_namespace.workspace_list.Snapshot = &source_namespace.empty_workspace_list,
prompt: ?*name_prompt.Prompt = null,
history: *const history_palette_state.State = &source_namespace.empty_history_palette,
suggestion: *const suggestion_state.State = &source_namespace.empty_suggestion,
proxy_tls_active: bool = false,
proxy_tls_scope: source_namespace.schema.ProxyScope = .exact,
proxy_system_trusted: bool = false,
system_metrics: ?client_model.SystemMetrics = null,
status_mode: widgets.status_bar.Mode = .normal,
copy_mode_active: bool = false,
bar_state: *const bars.State = &source_namespace.default_bars_state,
force: bool = false,
diagnostic: ?[]const u8 = null,
