const core = @import("telar-core");
const mailbox = @import("mailbox");
const data = @import("model");
const Snapshot = @This();

theme_name: []const u8,
icon_theme_name: []const u8,
active_tab: core.TabId,
tab_count: usize,
focused_pane: core.PaneId,
pane_count: usize,
pending_updates: usize,
draw_pending: bool,
media_pending: bool,
outbox: data.OutboxSnapshot,
inbox: mailbox.InboxSnapshot = .{},
capabilities: data.HostCapabilities,
zlib_support: data.EnvironmentSupport = .unknown,
sidebar_rendering: data.ResolvedSidebarRendering,
lua_used: usize,
lua_limit: usize,
kitty_store_bytes: usize,
toast_cache_bytes: usize,
sidebar_cache_bytes: usize,
icon_cache_bytes: usize,
modal_cache_bytes: usize,
pill_cache_bytes: usize = 0,
attachment_cache_bytes: usize,
screen_bytes: usize,
shared_expiries: u8,
shared_retire_latency: core.Timing,
heap: core.SnapshotSnapshot,
