const State = @This();
const source_namespace = @import("delivery.zig");
supported: bool = false,
cell_width: u16 = 0,
cell_height: u16 = 0,
next_host_id: u32 = 1,
partial: ?u8 = null,
abort_pending: bool = false,
delete_ids: [source_namespace.max_items * 2]u32 = undefined,
delete_count: u8 = 0,
delete_all_pending: bool = false,
