const WorkspaceActivation = @This();
const source_namespace = @import("types.zig");
pane_id: source_namespace.schema.PaneId,
location: source_namespace.schema.TabLocation,
workspace_revision_before: u64,
tabs_revision_before: u64,
active_tab_revision_before: u64,
panes_revision_before: u64,
copy_revision_before: u64,
copy_released: bool,
workspace_revision: u64,
tabs_revision: u64,
active_tab_revision: u64,
panes_revision: u64,
copy_revision: u64,
